import type { Metadata } from "next";
import React from "react";
import Provider from "@/app/components/Provider";

// Components
import Navbar from "@/app/components/Navbar";

// Styles
import { Ubuntu } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className} className="bg-light">
        <main className="container">
          <Provider>
            <Navbar />
            <section>{children}</section>
          </Provider>
        </main>
      </body>
    </html>
  );
}
